// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validar se as variáveis de ambiente estão definidas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Variáveis de ambiente VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY são obrigatórias');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Configurar para usar sessionStorage em vez de localStorage
    // Isso faz com que a sessão expire quando o navegador é fechado
    storage: window.sessionStorage,
    // Configurar para detectar quando a aba/janela é fechada
    detectSessionInUrl: false,
    // Configurar refresh automático do token
    autoRefreshToken: true,
    // Configurar para persistir sessão apenas durante a sessão do navegador
    persistSession: true,
    // Configurar flow type
    flowType: 'pkce'
  }
});